# -*- coding: utf-8 -*-
"""lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-lhso9Sr60qPjDazRQgaUSKcjl9WWEte

**Problem 1**
"""

import pandas as pd
obj = pd.Series([4, 7, -5, 3])
print(obj)
print(type(obj))
print(obj[obj%2==0])
print(obj+5 )
print(obj*2)

"""**Problem 2**"""

six = [i for i in range(1,1001) if '6' in str(i)] 
print(six)

"""**problem 3**"""

nums = [i for i in range(1,1001)]
string = "amar porashuna korte bhallage na"

n=len(string)
cnt=0

for i in range(1,n):
    if(string[i] == ' '):
       cnt+=1 
print("Spaces of the string is : ",cnt)

"""**problem 4**"""

string = "my name is obaidul qader"
for word in string:
    if word in ('a','e','i','o','u','A','I','E','O','U'):
        string = string.replace(word, '')
        
print("without vowel :", string)

"""**problem 5**"""

string = "my name is ikhtiar uddin mohammad bin bakhtiar khilji."
word=string.split(" ")
L=len(word)
for i in range (1,L):
    if(len(word[i])<5 ):
        print(word[i])

"""**problem 6**"""

string = "jibon e onek taka kamaite hobe"
words = string.split()
word_lengths = []
for word in words:
   word_lengths.append(len(word))
print(words)
print(word_lengths)

